[package]
name = "akimo_engine"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Sakul6499/Akimo-Engine"

[dependencies]
# X = { path = "../../X" }
